# Generated by Django 5.1.5 on 2025-02-01 12:09

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question_en",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="Question (English)"
                    ),
                ),
                (
                    "answer_en",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="Answer (English)"
                    ),
                ),
                ("translations", models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
